name: Spelling

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Spelling
        uses: check-spelling/check-spelling@main
        with:
          config: .github/spelling-config.yml

      - name: Download spelling artifact
        uses: actions/download-artifact@v4
        with:
          name: spelling-results

      - name: Report
        run: echo "Reporting spelling results"
